FROM python:3.11-slim
WORKDIR /app
COPY app_secure/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app_secure/ /app
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser \
 && mkdir -p /app/logs && chown -R appuser:appgroup /app

USER appuser
ENV FLASK_ENV=production
EXPOSE 5001
CMD ["gunicorn", "-b", "0.0.0.0:5001", "app:app"]
